# Generated by Django 6.1.1 on 2026-09-26 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Начало дуги')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец дуги')),
                ('current_avg', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='Ток средний, А')),
                ('current_min', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='Ток минимальный, А')),
                ('current_max', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='Ток максимальный, А')),
                ('voltage_avg', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Напряжение среднее, В')),
                ('pulse_freq', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Частота импульсов, Гц')),
                ('telemetry_complete', models.BooleanField(default=False, help_text='Узел шлёт запись порциями; при обрыве сети они ждут на узле и досылаются позже', verbose_name='Телеметрия получена полностью')),
            ],
            options={
                'verbose_name': 'Участок дуги',
                'verbose_name_plural': 'Участки дуги',
                'ordering': ['session', 'started_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начата')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Закончена')),
                ('status', models.CharField(choices=[('in_work', 'В работе'), ('done', 'Выполнена')], default='in_work', max_length=20, verbose_name='Статус')),
                ('size_before', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Размер до сварки, мм')),
                ('size_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Размер после сварки, мм')),
                ('measured_at', models.DateField(blank=True, null=True, verbose_name='Дата замера')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Выполнение операции',
                'verbose_name_plural': 'Выполнение операций',
                'ordering': ['weld', 'operation'],
            },
        ),
        migrations.CreateModel(
            name='PartInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=100, verbose_name='Заводской номер')),
                ('kind', models.CharField(choices=[('штатное', 'Штатное изделие'), ('свидетель', 'Образец-свидетель')], default='штатное', max_length=20, verbose_name='Вид')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Заведено')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код операции по маршруту')),
                ('source', models.CharField(blank=True, help_text='вручную / выгрузка / API MES', max_length=50, verbose_name='Откуда получено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Заведено')),
            ],
            options={
                'verbose_name': 'Код маршрутного листа',
                'verbose_name_plural': 'Коды маршрутных листов',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Weld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_work', 'В работе'), ('done', 'Сварен'), ('accepted', 'Принят'), ('rejected', 'Забракован')], default='in_work', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Заведён')),
            ],
            options={
                'verbose_name': 'Сварной шов',
                'verbose_name_plural': 'Сварные швы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeldingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welder_name', models.CharField(blank=True, max_length=200, verbose_name='Сварщик (снимок)')),
                ('mode', models.CharField(choices=[('по техпроцессу', 'По техпроцессу'), ('отработка', 'Отработка режимов'), ('прихватка', 'Прихватка и вспомогательные работы')], default='по техпроцессу', max_length=20, verbose_name='Режим записи')),
                ('route_code_raw', models.CharField(blank=True, max_length=50, verbose_name='Код с маршрутного листа')),
                ('started_at', models.DateTimeField(verbose_name='Начата')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Закончена')),
            ],
            options={
                'verbose_name': 'Сеанс сварки',
                'verbose_name_plural': 'Сеансы сварки',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WeldPassRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveSmallIntegerField(verbose_name='№ прохода')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начат')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Закончен')),
                ('arc_time', models.DurationField(blank=True, help_text='Сумма сегментов дуги без пауз — по нему считается фактическая скорость', null=True, verbose_name='Чистое время горения дуги')),
                ('match_source', models.CharField(choices=[('вручную', 'Указано человеком'), ('датчик', 'По датчику вращения'), ('ток', 'Подтверждено скачком тока'), ('пауза', 'Подтверждено остановкой'), ('расчёт', 'Только по накопленному времени дуги')], default='расчёт', max_length=20, verbose_name='Как определена граница прохода')),
            ],
            options={
                'verbose_name': 'Проход (факт)',
                'verbose_name_plural': 'Проходы (факт)',
                'ordering': ['run', 'no'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('промежуточный', 'Промежуточный'), ('окончательный', 'Окончательный')], max_length=20, verbose_name='Вид контроля')),
                ('method', models.CharField(choices=[('РК', 'Радиографический'), ('ВИК', 'Визуально-измерительный'), ('УЗК', 'Ультразвуковой'), ('ПВК', 'Капиллярный'), ('МК', 'Металлографический')], max_length=10, verbose_name='Метод')),
                ('specimen', models.CharField(choices=[('шов', 'Сам шов'), ('свидетель', 'Образец-свидетель'), ('вырезка', 'Вырезка из шва')], default='шов', max_length=20, verbose_name='Объект контроля')),
                ('result', models.CharField(choices=[('годен', 'Годен'), ('исправление', 'Требует исправления'), ('брак', 'Брак')], max_length=20, verbose_name='Результат')),
                ('defects', models.JSONField(blank=True, default=list, verbose_name='Дефекты')),
                ('report_no', models.CharField(blank=True, max_length=50, verbose_name='№ заключения')),
                ('inspected_at', models.DateField(blank=True, null=True, verbose_name='Дата контроля')),
                ('inspector_name', models.CharField(blank=True, max_length=200, verbose_name='Контролёр (снимок)')),
                ('conclusion', models.TextField(blank=True, verbose_name='Заключение')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL, verbose_name='Контролёр')),
            ],
            options={
                'verbose_name': 'Заключение контроля',
                'verbose_name_plural': 'Заключения контроля',
                'ordering': ['-inspected_at'],
            },
        ),
    ]
