# Generated by Django 6.1.1 on 2026-09-26 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_remove_equipment_workshop_equipment_node_id_and_more'),
        ('technology', '0001_initial'),
        ('welders', '0002_welder_personnel_no_welder_rfid_uid'),
        ('welding', '0001_initial'),
        ('weldingcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationrun',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='weldingcards.weldingcard', verbose_name='Техкарта'),
        ),
        migrations.AddField(
            model_name='operationrun',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='equipment.equipment', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='operationrun',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='technology.operation', verbose_name='Операция'),
        ),
        migrations.AddField(
            model_name='operationrun',
            name='welder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='welders.welder', verbose_name='Сварщик'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='welding.operationrun', verbose_name='Выполнение операции'),
        ),
        migrations.AddField(
            model_name='partinstance',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='technology.part', verbose_name='Деталь'),
        ),
        migrations.AddField(
            model_name='partinstance',
            name='witness_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='witnesses', to='welding.partinstance', verbose_name='Свидетель к изделию'),
        ),
        migrations.AddField(
            model_name='routecode',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_codes', to='welding.partinstance', verbose_name='Изделие'),
        ),
        migrations.AddField(
            model_name='routecode',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_codes', to='technology.operation', verbose_name='Операция'),
        ),
        migrations.AddField(
            model_name='routecode',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_codes', to='technology.part', verbose_name='Деталь'),
        ),
        migrations.AddField(
            model_name='weld',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welds', to='welding.partinstance', verbose_name='Изделие'),
        ),
        migrations.AddField(
            model_name='weld',
            name='seam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='welds', to='technology.seamspec', verbose_name='Шов по чертежу'),
        ),
        migrations.AddField(
            model_name='operationrun',
            name='weld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='welding.weld', verbose_name='Шов'),
        ),
        migrations.AddField(
            model_name='weldingsession',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='equipment.equipment', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='weldingsession',
            name='operation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='welding.operationrun', verbose_name='Выполнение операции'),
        ),
        migrations.AddField(
            model_name='weldingsession',
            name='welder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='welders.welder', verbose_name='Сварщик'),
        ),
        migrations.AddField(
            model_name='arcrun',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcs', to='welding.weldingsession', verbose_name='Сеанс'),
        ),
        migrations.AddField(
            model_name='weldpassrun',
            name='planned_pass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='weldingcards.weldpass', verbose_name='Проход по карте'),
        ),
        migrations.AddField(
            model_name='weldpassrun',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='welding.operationrun', verbose_name='Выполнение операции'),
        ),
        migrations.AddField(
            model_name='arcrun',
            name='pass_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arcs', to='welding.weldpassrun', verbose_name='Проход'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['result'], name='welding_ins_result_7e2f22_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['method', 'result'], name='welding_ins_method_b12873_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['specimen'], name='welding_ins_specime_720f93_idx'),
        ),
        migrations.AddIndex(
            model_name='partinstance',
            index=models.Index(fields=['kind'], name='welding_par_kind_da5103_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partinstance',
            unique_together={('part', 'serial_no')},
        ),
        migrations.AddIndex(
            model_name='weld',
            index=models.Index(fields=['status'], name='welding_wel_status_246d54_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weld',
            unique_together={('instance', 'seam')},
        ),
        migrations.AddIndex(
            model_name='operationrun',
            index=models.Index(fields=['card'], name='welding_ope_card_id_f07773_idx'),
        ),
        migrations.AddIndex(
            model_name='operationrun',
            index=models.Index(fields=['welder', 'started_at'], name='welding_ope_welder__39dddf_idx'),
        ),
        migrations.AddIndex(
            model_name='operationrun',
            index=models.Index(fields=['equipment', 'started_at'], name='welding_ope_equipme_a53262_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='operationrun',
            unique_together={('weld', 'operation')},
        ),
        migrations.AddIndex(
            model_name='weldingsession',
            index=models.Index(fields=['equipment', 'started_at'], name='welding_wel_equipme_002280_idx'),
        ),
        migrations.AddIndex(
            model_name='weldingsession',
            index=models.Index(fields=['welder', 'started_at'], name='welding_wel_welder__6ff124_idx'),
        ),
        migrations.AddIndex(
            model_name='weldingsession',
            index=models.Index(fields=['mode'], name='welding_wel_mode_d03691_idx'),
        ),
        migrations.AddIndex(
            model_name='weldpassrun',
            index=models.Index(fields=['started_at', 'finished_at'], name='welding_wel_started_b4554f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weldpassrun',
            unique_together={('run', 'no')},
        ),
        migrations.AddIndex(
            model_name='arcrun',
            index=models.Index(fields=['session', 'started_at'], name='welding_arc_session_8d43fd_idx'),
        ),
        migrations.AddIndex(
            model_name='arcrun',
            index=models.Index(fields=['pass_run'], name='welding_arc_pass_ru_937a12_idx'),
        ),
    ]
