# Generated by Django 6.1.1 on 2026-09-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeldingMethod',
            fields=[
                ('id', models.SlugField(max_length=20, primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('designation', models.CharField(blank=True, help_text='Без суффикса п/б — он подставляется по наличию присадки', max_length=20, verbose_name='Базовое обозначение')),
                ('process', models.CharField(choices=[('tig', 'Неплавящийся электрод в защитном газе'), ('mig', 'Плавящийся электрод в защитном газе'), ('plasma', 'Плазменная'), ('ebw', 'Электронно-лучевая'), ('diff', 'Диффузионная'), ('contact', 'Контактная'), ('laser', 'Лазерная')], max_length=20, verbose_name='Процесс')),
                ('tpl_key', models.CharField(blank=True, max_length=30, verbose_name='Шаблон бланка')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Используется')),
            ],
            options={
                'verbose_name': 'Способ сварки',
                'verbose_name_plural': 'Способы сварки',
                'ordering': ['order'],
            },
        ),
    ]
