# Generated by Django 6.1.1 on 2026-09-26 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='№ по чертежу')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('drawing_no', models.CharField(blank=True, max_length=100, verbose_name='Обозначение чертежа')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='В производстве')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SeamSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='№ шва по чертежу')),
                ('joint_type', models.CharField(blank=True, max_length=50, verbose_name='Тип соединения')),
                ('thickness_1', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Толщина позиции 1, мм')),
                ('thickness_2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Толщина позиции 2, мм')),
                ('pos_1', models.CharField(blank=True, max_length=50, verbose_name='Позиция 1')),
                ('mass_1', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Масса позиции 1, кг')),
                ('pos_2', models.CharField(blank=True, max_length=50, verbose_name='Позиция 2')),
                ('mass_2', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Масса позиции 2, кг')),
                ('seam_type', models.CharField(blank=True, help_text='прямой / кольцевой', max_length=20, verbose_name='Вид шва')),
                ('seam_diameter', models.DecimalField(blank=True, decimal_places=2, help_text='Для кольцевого. Нужен для пересчёта угловых скоростей', max_digits=9, null=True, verbose_name='Диаметр шва, мм')),
                ('seam_length', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Длина шва, мм')),
                ('material_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='materials.material', verbose_name='Материал 1')),
                ('material_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='materials.material', verbose_name='Материал 2')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seams', to='technology.part', verbose_name='Деталь')),
            ],
            options={
                'verbose_name': 'Шов по чертежу',
                'verbose_name_plural': 'Швы по чертежу',
                'ordering': ['part', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='№ операции')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Наименование операции')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='По нему операции идут в техпроцессе, а не по номеру', verbose_name='Порядок выполнения')),
                ('required_controls', models.JSONField(blank=True, default=list, verbose_name='Контроль после операции')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='technology.part', verbose_name='Деталь')),
                ('seam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='technology.seamspec', verbose_name='Шов')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['part', 'order', 'number'],
            },
        ),
        migrations.AddIndex(
            model_name='seamspec',
            index=models.Index(fields=['material_1', 'thickness_1'], name='technology__materia_f40987_idx'),
        ),
        migrations.AddIndex(
            model_name='seamspec',
            index=models.Index(fields=['thickness_1'], name='technology__thickne_663a45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seamspec',
            unique_together={('part', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='operation',
            unique_together={('part', 'number')},
        ),
    ]
