# Generated by Django 6.1.1 on 2026-09-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='drawing_no',
        ),
    ]
