# Generated by Django 6.1.1 on 2026-09-24 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('methods', '0001_initial'),
        ('welders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controls', models.JSONField(default=list, verbose_name='Виды контроля')),
                ('status', models.CharField(choices=[('draft', 'Черновик / заявки'), ('testing', 'Ждём испытаний'), ('protocol', 'Составление протокола'), ('review', 'Согласование'), ('done', 'Аттестован')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('attested_at', models.DateField(blank=True, null=True, verbose_name='Дата аттестации')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('protocol_no', models.CharField(blank=True, max_length=50, verbose_name='№ протокола')),
                ('certificate_no', models.CharField(blank=True, max_length=50, verbose_name='№ удостоверения')),
                ('kind', models.CharField(choices=[('первичная', 'Первичная'), ('периодическая', 'Периодическая')], default='первичная', max_length=20, verbose_name='Вид аттестации')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.materialgroup', verbose_name='Группа материала')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='methods.weldingmethod', verbose_name='Способ сварки')),
                ('welder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attestations', to='welders.welder', verbose_name='Сварщик')),
            ],
            options={
                'verbose_name': 'Аттестация',
                'verbose_name_plural': 'Аттестации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttestationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_no', models.CharField(max_length=50, verbose_name='№ образца')),
                ('uniform', models.BooleanField(default=False, verbose_name='Однородное')),
                ('thickness_min', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Толщина от')),
                ('thickness_max', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Толщина до')),
                ('wire_text', models.CharField(blank=True, max_length=100, verbose_name='Электрод / проволока (снимок)')),
                ('flux_text', models.CharField(blank=True, max_length=100, verbose_name='Флюс (снимок)')),
                ('gas_text', models.CharField(blank=True, max_length=100, verbose_name='Защитный газ (снимок)')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='Положение')),
                ('preheat', models.CharField(blank=True, max_length=50, verbose_name='Подогрев')),
                ('heat_treatment', models.CharField(blank=True, max_length=50, verbose_name='Термообработка')),
                ('attestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='attestation.attestation', verbose_name='Аттестация')),
                ('flux', models.ForeignKey(blank=True, limit_choices_to={'kind': 'flux'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='materials.gasflux', verbose_name='Флюс')),
                ('gas', models.ForeignKey(blank=True, limit_choices_to={'kind': 'gas'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='materials.gasflux', verbose_name='Защитный газ')),
                ('material1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='materials.material', verbose_name='Материал 1')),
                ('material2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='materials.material', verbose_name='Материал 2')),
                ('wire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='materials.fillermaterial', verbose_name='Электрод / проволока')),
            ],
            options={
                'verbose_name': 'Образец аттестации',
                'verbose_name_plural': 'Образцы аттестации',
            },
        ),
        migrations.CreateModel(
            name='AttestationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('th_from', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Толщина от, мм')),
                ('th_to', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Толщина до, мм')),
                ('required_output', models.JSONField(default=dict, verbose_name='Требования')),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='materials.materialgroup')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='methods.weldingmethod')),
            ],
            options={
                'verbose_name': 'Правило аттестации',
                'verbose_name_plural': 'Библиотека правил',
                'ordering': ['method', 'group', 'th_from'],
            },
        ),
    ]
