# Generated by Django 6.1.1 on 2026-09-26 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0001_initial'),
        ('materials', '0001_initial'),
        ('methods', '0001_initial'),
        ('welders', '0002_welder_personnel_no_welder_rfid_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestation',
            name='chairman',
            field=models.CharField(blank=True, max_length=200, verbose_name='Председатель комиссии'),
        ),
        migrations.AddField(
            model_name='attestation',
            name='conclusion',
            field=models.TextField(blank=True, help_text='Поле 28 протокола', verbose_name='Заключение о допуске'),
        ),
        migrations.AddField(
            model_name='attestation',
            name='head_btk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Начальник БТК'),
        ),
        migrations.AddField(
            model_name='attestation',
            name='head_shop',
            field=models.CharField(blank=True, max_length=200, verbose_name='Начальник цеха'),
        ),
        migrations.AddField(
            model_name='attestation',
            name='practical_eval',
            field=models.CharField(blank=True, help_text='Поле 26 протокола', max_length=50, verbose_name='Оценка практических навыков'),
        ),
        migrations.AddField(
            model_name='attestationitem',
            name='bend_angle',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Поле 23', max_digits=5, null=True, verbose_name='Угол загиба, °'),
        ),
        migrations.AddField(
            model_name='attestationitem',
            name='impact_strength',
            field=models.CharField(blank=True, help_text='Поле 24 — KCU или KCV с температурой', max_length=100, verbose_name='Ударная вязкость'),
        ),
        migrations.AddField(
            model_name='attestationitem',
            name='metallography_protocol',
            field=models.CharField(blank=True, help_text='Поле 21', max_length=100, verbose_name='Металлография, № протокола'),
        ),
        migrations.AddField(
            model_name='attestationitem',
            name='other_methods',
            field=models.CharField(blank=True, help_text='Поле 25', max_length=200, verbose_name='Другие методы'),
        ),
        migrations.AddField(
            model_name='attestationitem',
            name='physical_protocol',
            field=models.CharField(blank=True, help_text='Поле 20 — РК или УЗК', max_length=100, verbose_name='Физические методы, № протокола'),
        ),
        migrations.AddField(
            model_name='attestationitem',
            name='requirements_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Снимок требований'),
        ),
        migrations.AddField(
            model_name='attestationitem',
            name='tensile_strength',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Поле 22 — из протокола испытаний', max_digits=6, null=True, verbose_name='Предел прочности, кгс/мм²'),
        ),
        migrations.AddField(
            model_name='attestationitem',
            name='vik_result',
            field=models.CharField(blank=True, help_text='Поле 19', max_length=100, verbose_name='ВИК'),
        ),
        migrations.AlterField(
            model_name='attestationitem',
            name='material2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='materials.material', verbose_name='Материал 2'),
        ),
        migrations.AddIndex(
            model_name='attestation',
            index=models.Index(fields=['valid_until'], name='attestation_valid_u_4851dc_idx'),
        ),
        migrations.AddIndex(
            model_name='attestation',
            index=models.Index(fields=['status'], name='attestation_status_17aaa2_idx'),
        ),
        migrations.AddIndex(
            model_name='attestation',
            index=models.Index(fields=['welder', 'method'], name='attestation_welder__656805_idx'),
        ),
    ]
