# Generated by Django 6.1.1 on 2026-09-26 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Номер')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='workshops.workshop', verbose_name='Цех')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
                'ordering': ['workshop', 'number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер поста')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='В работе')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workstations', to='workshops.section', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Рабочее место',
                'verbose_name_plural': 'Рабочие места',
                'ordering': ['section', 'number'],
            },
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('workshop', 'number'), name='unique_section_number_per_workshop'),
        ),
        migrations.AddConstraint(
            model_name='workstation',
            constraint=models.UniqueConstraint(fields=('section', 'number'), name='unique_workstation_number_per_section'),
        ),
    ]
