# Generated by Django 6.1.1 on 2026-09-24 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('methods', '0001_initial'),
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Единица')),
                ('level', models.CharField(choices=[('card', 'На всю карту'), ('pass', 'На каждый проход')], max_length=10, verbose_name='Уровень')),
                ('printed', models.BooleanField(default=True, verbose_name='Печатать в техкарте')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Параметр оборудования',
                'verbose_name_plural': 'Параметры оборудования',
                'ordering': ['level', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpeedUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=20, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=20, verbose_name='Обозначение')),
                ('is_angular', models.BooleanField(default=False, help_text='Для пересчёта в м/ч нужен диаметр шва (об/мин, град/с)', verbose_name='Угловая')),
                ('to_m_per_h', models.DecimalField(blank=True, decimal_places=8, help_text='Для линейных: во сколько раз больше м/ч. Для угловых: множитель к π·D·об (D в метрах)', max_digits=14, null=True, verbose_name='Коэффициент пересчёта в м/ч')),
            ],
            options={
                'verbose_name': 'Единица скорости',
                'verbose_name_plural': 'Единицы скорости',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('has_pulse', models.BooleanField(default=False, verbose_name='Импульсный режим')),
                ('is_active', models.BooleanField(default=True, verbose_name='В работе')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='methods.weldingmethod', verbose_name='Способ сварки')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='workshops.workshop', verbose_name='Цех')),
                ('parameters', models.ManyToManyField(blank=True, to='equipment.equipmentparameter', verbose_name='Дополнительные параметры')),
                ('speed_units', models.ManyToManyField(blank=True, help_text='Кольцевой шов — об/мин, прямой — м/ч; у установки может быть несколько', to='equipment.speedunit', verbose_name='Рабочие единицы скорости')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['method', 'name'],
            },
        ),
    ]
