# Generated by Django 6.1.1 on 2026-09-26 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('workshops', '0002_section_workstation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='workshop',
        ),
        migrations.AddField(
            model_name='equipment',
            name='node_id',
            field=models.CharField(blank=True, help_text='MAC или серийный номер платы WT32-ETH01', max_length=50, null=True, unique=True, verbose_name='Идентификатор узла телеметрии'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='node_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP узла'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='workshops.workstation', verbose_name='Рабочее место'),
        ),
    ]
