# Generated by Django 6.1.1 on 2026-09-24 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('education', models.CharField(max_length=200, verbose_name='Образование')),
                ('welding_since', models.DateField(blank=True, null=True, verbose_name='Начало стажа по сварке')),
                ('rank', models.CharField(blank=True, max_length=20, verbose_name='Квалификационный разряд')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welders', to='workshops.workshop', verbose_name='Цех / место работы')),
            ],
            options={
                'verbose_name': 'Сварщик',
                'verbose_name_plural': 'Сварщики',
                'ordering': ['fio'],
            },
        ),
    ]
