# Generated by Django 6.1.1 on 2026-09-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='welder',
            name='personnel_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='Табельный номер'),
        ),
        migrations.AddField(
            model_name='welder',
            name='rfid_uid',
            field=models.CharField(blank=True, help_text='Канонический ключ — hex. Печатный номер на карте — тот же UID в десятичном виде с нулями до 10 знаков', max_length=16, null=True, unique=True, verbose_name='UID карты (hex)'),
        ),
    ]
