# Generated by Django 6.1.1 on 2026-09-26 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_remove_equipment_workshop_equipment_node_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('ремонт', 'Ремонт'), ('диагностика', 'Диагностика'), ('неисправность', 'Неисправность'), ('то', 'Плановое ТО')], max_length=20, verbose_name='Причина')),
                ('priority', models.CharField(choices=[('низкая', 'Низкая'), ('средняя', 'Средняя'), ('высокая', 'Высокая')], default='средняя', max_length=20, verbose_name='Срочность')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('open', 'Подана'), ('in_work', 'В работе'), ('done', 'Выполнена'), ('rejected', 'Отклонена')], default='open', max_length=20, verbose_name='Статус')),
                ('author_name', models.CharField(blank=True, max_length=200, verbose_name='Заявитель (снимок)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Подана')),
                ('closed_by_name', models.CharField(blank=True, max_length=200, verbose_name='Кто закрыл (снимок)')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыта')),
                ('resolution', models.TextField(blank=True, verbose_name='Что сделано')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_service_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кто закрыл')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='equipment.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Заявка на обслуживание',
                'verbose_name_plural': 'Заявки на обслуживание',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='service_ser_status_0aa203_idx'), models.Index(fields=['equipment', 'status'], name='service_ser_equipme_b54309_idx')],
            },
        ),
    ]
