# Generated by Django 6.1.1 on 2026-09-24 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Группа материалов',
                'verbose_name_plural': 'Группы материалов',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FillerMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=100, verbose_name='Марка')),
                ('kind', models.CharField(choices=[('присадочная проволока', 'Присадочная проволока'), ('электрод', 'Покрытый электрод'), ('вольфрам', 'Вольфрамовый электрод')], max_length=30, verbose_name='Тип')),
                ('diameter', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Диаметр, мм')),
            ],
            options={
                'verbose_name': 'Сварочный материал',
                'verbose_name_plural': 'Сварочные материалы',
                'ordering': ['kind', 'marka'],
                'unique_together': {('marka', 'diameter', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='GasFlux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('gas', 'Защитный / плазмообразующий газ'), ('flux', 'Флюс')], max_length=10, verbose_name='Тип')),
                ('value', models.CharField(max_length=200, verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Газ / флюс',
                'verbose_name_plural': 'Газы и флюсы',
                'ordering': ['kind', 'value'],
                'unique_together': {('kind', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=100, verbose_name='Марка')),
                ('tensile_strength', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Предел прочности, кгс/мм²')),
                ('analogs', models.ManyToManyField(blank=True, help_text='Марки со схожей свариваемостью — на их режимы можно ориентироваться', to='materials.material', verbose_name='Материалы-аналоги')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='materials.materialgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Основной материал',
                'verbose_name_plural': 'Основные материалы',
                'ordering': ['marka'],
            },
        ),
        migrations.CreateModel(
            name='MaterialPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('fillers', models.ManyToManyField(blank=True, related_name='pairs', to='materials.fillermaterial', verbose_name='Допустимые присадочные материалы')),
                ('fluxes', models.ManyToManyField(blank=True, limit_choices_to={'kind': 'flux'}, related_name='pairs', to='materials.gasflux', verbose_name='Допустимые флюсы')),
                ('material_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_first', to='materials.material', verbose_name='Материал 1')),
                ('material_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_second', to='materials.material', verbose_name='Материал 2')),
            ],
            options={
                'verbose_name': 'Сочетание материалов',
                'verbose_name_plural': 'Сочетания материалов',
                'ordering': ['material_1__marka', 'material_2__marka'],
                'unique_together': {('material_1', 'material_2')},
            },
        ),
    ]
