# Generated by Django 6.1.1 on 2026-09-26 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_remove_equipment_workshop_equipment_node_id_and_more'),
        ('materials', '0001_initial'),
        ('methods', '0001_initial'),
        ('technology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeldingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=50, verbose_name='№ карты')),
                ('revision', models.PositiveSmallIntegerField(default=1, help_text='Растёт при переиздании карты. Прослеживаемость хранит ссылку на ту карту, по которой реально варили', verbose_name='Редакция')),
                ('welding_mode', models.CharField(blank=True, choices=[('непрерывный', 'Непрерывный'), ('импульсный', 'Импульсный')], default='непрерывный', max_length=20, verbose_name='Режим сварки')),
                ('tungsten_text', models.CharField(blank=True, max_length=100, verbose_name='Вольфрамовый электрод (снимок)')),
                ('filler_text', models.CharField(blank=True, max_length=100, verbose_name='Присадочный материал (снимок)')),
                ('shield_gas_text', models.CharField(blank=True, max_length=100, verbose_name='Защитный газ (снимок)')),
                ('backing_gas_text', models.CharField(blank=True, max_length=100, verbose_name='Газ на поддув (снимок)')),
                ('plasma_gas_text', models.CharField(blank=True, max_length=100, verbose_name='Плазмообразующий газ (снимок)')),
                ('flux_text', models.CharField(blank=True, max_length=100, verbose_name='Флюс (снимок)')),
                ('plasma_nozzle_d', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Ø плазмообразующего сопла, мм')),
                ('heat_treatment', models.CharField(blank=True, max_length=200, verbose_name='Термообработка')),
                ('groove_type', models.CharField(blank=True, max_length=20, verbose_name='Тип разделки')),
                ('groove_angle', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Угол разделки, °')),
                ('groove_gap', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Зазор b, мм')),
                ('groove_root', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Притупление c, мм')),
                ('groove_cap', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Усиление g, мм')),
                ('groove_root_cap', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Корень g₁, мм')),
                ('groove_width', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Ширина шва f, мм')),
                ('groove_svg', models.TextField(blank=True, verbose_name='Эскиз (SVG)')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Прочие параметры')),
                ('is_released', models.BooleanField(default=False, help_text='Черновик правится свободно; выпущенная карта — документ, по ней уже варят', verbose_name='Выпущена')),
                ('author_name', models.CharField(blank=True, max_length=200, verbose_name='Автор (снимок)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welding_cards', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('backing_gas', models.ForeignKey(blank=True, limit_choices_to={'kind': 'gas'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='materials.gasflux', verbose_name='Защитный газ на поддув')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='equipment.equipment', verbose_name='Оборудование')),
                ('filler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='materials.fillermaterial', verbose_name='Присадочный материал')),
                ('flux', models.ForeignKey(blank=True, limit_choices_to={'kind': 'flux'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='materials.gasflux', verbose_name='Флюс')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='methods.weldingmethod', verbose_name='Способ сварки')),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='card', to='technology.operation', verbose_name='Операция')),
                ('plasma_gas', models.ForeignKey(blank=True, limit_choices_to={'kind': 'gas'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='materials.gasflux', verbose_name='Плазмообразующий газ')),
                ('shield_gas', models.ForeignKey(blank=True, limit_choices_to={'kind': 'gas'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='materials.gasflux', verbose_name='Защитный газ в горелку')),
                ('tungsten', models.ForeignKey(blank=True, limit_choices_to={'kind': 'вольфрам'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='materials.fillermaterial', verbose_name='Вольфрамовый электрод')),
            ],
            options={
                'verbose_name': 'Технологическая карта',
                'verbose_name_plural': 'Технологические карты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeldPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveSmallIntegerField(verbose_name='№ прохода')),
                ('current_min', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='Ток от, А')),
                ('current_max', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='Ток до, А')),
                ('voltage_min', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Напряжение от, В')),
                ('voltage_max', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Напряжение до, В')),
                ('speed_raw_min', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Скорость от (в ед. установки)')),
                ('speed_raw_max', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Скорость до (в ед. установки)')),
                ('speed_min', models.DecimalField(blank=True, decimal_places=3, help_text='Считается порталом, используется для поиска и статистики', max_digits=10, null=True, verbose_name='Скорость от, м/ч')),
                ('speed_max', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Скорость до, м/ч')),
                ('speed_required', models.BooleanField(default=False, help_text='У ручных способов скорость справочная; флаг включает контроль по телеметрии', verbose_name='Скорость обязательна к соблюдению')),
                ('wire_speed_min', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Подача проволоки от, м/мин')),
                ('wire_speed_max', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Подача проволоки до, м/мин')),
                ('gas_flow_min', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Расход защитного газа от, л/мин')),
                ('gas_flow_max', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Расход защитного газа до, л/мин')),
                ('backing_flow_min', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Расход газа на поддув от, л/мин')),
                ('backing_flow_max', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Расход газа на поддув до, л/мин')),
                ('plasma_flow_min', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Расход плазмообразующего от, л/мин')),
                ('plasma_flow_max', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Расход плазмообразующего до, л/мин')),
                ('filler_text', models.CharField(blank=True, max_length=100, verbose_name='Присадка на проходе (снимок)')),
                ('filler_diameter', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Диаметр присадки, мм')),
                ('pulse_current', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='Ток импульса, А')),
                ('pulse_time', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Время импульса, с')),
                ('pause_current', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='Ток паузы, А')),
                ('pause_time', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Время паузы, с')),
                ('beam_current', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ток луча, мА')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Прочие параметры прохода')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='weldingcards.weldingcard', verbose_name='Карта')),
                ('filler', models.ForeignKey(blank=True, help_text='Заполняется, только если отличается от указанной в карте', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='materials.fillermaterial', verbose_name='Присадка на проходе')),
                ('speed_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='equipment.speedunit', verbose_name='Единица скорости')),
            ],
            options={
                'verbose_name': 'Проход',
                'verbose_name_plural': 'Проходы',
                'ordering': ['card', 'no'],
            },
        ),
        migrations.AddIndex(
            model_name='weldingcard',
            index=models.Index(fields=['method'], name='weldingcard_method__ee6ab8_idx'),
        ),
        migrations.AddIndex(
            model_name='weldingcard',
            index=models.Index(fields=['equipment'], name='weldingcard_equipme_cbb095_idx'),
        ),
        migrations.AddIndex(
            model_name='weldingcard',
            index=models.Index(fields=['is_released'], name='weldingcard_is_rele_13ad8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weldpass',
            unique_together={('card', 'no')},
        ),
    ]
